version: 1
groups:
  - annotation: GoogleAnalytics settings
    options:
      - key: googleanalytics.id
        required: true
        placeholder: UA-000000000-1
        validators: not_empty
        description: |
          Google tag ID(`G-*`) for Google Analytics 4, the Tracking ID(`UA-*`)
          for Universal Analytics, or container ID(`GTM-*`) for Google Tag
          Manager.

      - key: googleanalytics.download_handler
        default: ckan.views.resource:download
        description: |
          Import path of the CKAN view that handles resource downloads. It can
          be used in combination with plugins that replace download
          view(`ckanext-cloudstorage`, `ckanext-s3filestore`).

      - key: googleanalytics.tracking_mode
        experimental: true
        example: gtag
        description: |
          Defines the type of code snippet embedded into the page. Can be set
          to `ga`(enables `googleanalytics.js`), `gtag`(enables `gtag.js`), or
          `gtm`(enables Google Tag Manager). The plugin will check
          `googleanalytics.id` and set appropriate value depending on the
          prefix: `G-` enables `gtag`, `UA-` enables `ga` mode, and `GTM-`
          enables Google Tag Manager.

          Use this option only if you know better which snippet you need. In
          future, after dropping UniversalAnalytics, this option may be
          removed.

      - key: googleanalytics.account

      - key: googleanalytics.profile_id

      - key: googleanalytics.domain
        default: auto

      - key: googleanalytics.credentials.path

      - key: googleanalytics.fields
        default: "{}"

      - key: googleanalytics.linked_domains
        default: ""

      - key: googleanalytics.enable_user_id
        type: bool

      - key: googleanalytics_resource_prefix
        default: "/downloads/"

      - key: googleanalytics.recent_view_days
        default: 14

      - key: googleanalytics.measurement_protocol.id
      - key: googleanalytics.measurement_protocol.client_id
      - key: googleanalytics.measurement_protocol.client_secret
      - key: googleanalytics.measurement_protocol.track_downloads
